/*
 * Copyright (C) 2000 Rik Hemsley (rikkus) <rik@kde.org>. All rights reserved.
 *
LICENSE
 */

/* XPM */
static const char * const px_close[] = {
/* columns rows colors chars-per-pixel */
"16 16 5 1",
"  c Gray0",
". c #a0a0a0",
"X c Gray76",
"o c Gray100",
"O c None",
/* pixels */
"OOOOOOOOOOOOOOOO",
"OO  OOOOOOOO  OO",
"O Oo OOOOOO oO O",
"O oOo OOOO oOo O",
"OO oOo OO oOo OO",
"OOO oOo  oOo OOO",
"OOOO oOoOOo OOOO",
"OOOOO oOoO OOOOO",
"OOOOO OoOo OOOOO",
"OOOO oOOoOo OOOO",
"OOO oOo  oOo OOO",
"OO oOo OO oOo OO",
"O oOo OOOO oOo O",
"O Oo OOOOOO oO O",
"OO  OOOOOOOO  OO",
"OOOOOOOOOOOOOOOO"
};
/* XPM */
static const char * const px_playlist[] = {
/* columns rows colors chars-per-pixel */
"16 16 15 1",
"  c Gray0",
". c Gray41",
"X c Gray48",
"o c #8e8e8e",
"O c #979797",
"+ c #9f9f9f",
"@ c Gray70",
"# c Gray76",
"$ c #d7d7d7",
"% c gainsboro",
"& c #e4e4e4",
"* c Gray92",
"= c #f3f3f3",
"- c #fefefe",
"; c None",
/* pixels */
";;;;;;;;;;;;;;;;",
";;;;;;;;;;;;;;;;",
";;;;;   ;;;;;;;;",
";;;; ;-; ;;;;;;;",
";;; ;-;-; ;;;;;;",
";; ;-;-;-; ;;;;;",
";; -;-;-;- ;;;;;",
";; ;-;-;-; ;;;;;",
";;; ;-;-; ;;;;;;",
";;;; ;-;   ;;;;;",
";;;;;   ;   ;;;;",
";;;;;;;;;;   ;;;",
";;;;;;;;;;;   ;;",
";;;;;;;;;;;; ;;;",
";;;;;;;;;;;;;;;;",
";;;;;;;;;;;;;;;;"
};
/* XPM */
static const char * const px_album[] = {
/* columns rows colors chars-per-pixel */
"16 16 78 1",
"  c Gray0",
". c Gray5",
"X c Gray7",
"o c #1b1b1b",
"O c #272727",
"+ c #7c7c7c",
"@ c #132dcd",
"# c #273fe3",
"$ c #4e5ec1",
"% c #425fdf",
"& c #5568e3",
"* c #6dd47f",
"= c #7e8e85",
"- c #7dab84",
"; c #5ce78b",
": c #9f7471",
"> c #ad4f5c",
", c #b65362",
"< c #a47c76",
"1 c #c06956",
"2 c #c76475",
"3 c #d90db9",
"4 c #eb1fcc",
"5 c #e84dba",
"6 c #db53c9",
"7 c #bc8a35",
"8 c #ae887f",
"9 c #df9e3a",
"0 c #efba5e",
"q c #f0ba60",
"w c #ecf163",
"e c #9d9c88",
"r c #84ab8f",
"t c #8eb598",
"y c #a79190",
"u c #a5a5a5",
"i c #a7a2bc",
"p c #acb3be",
"a c #bdb5af",
"s c #b7b7b7",
"d c #bcb5b4",
"f c #8084c2",
"g c #acb7c1",
"h c #b9b4c6",
"j c #8beba4",
"k c #b4d2c0",
"l c #bad5cf",
"z c #c49794",
"x c #caa9a7",
"c c #d1a5a5",
"v c #dcaaa9",
"b c #d7aebb",
"n c #d5bead",
"m c #e8aeb4",
"M c #ec9fce",
"N c #ec99d3",
"B c #d6ca8e",
"V c #d0cb94",
"C c #cfc8ba",
"Z c #d6c4ad",
"A c #d8c0ad",
"S c #d4c6b6",
"D c #dccfbf",
"F c #d5d4a1",
"G c #e3c593",
"H c #e8c799",
"J c #e4e5ba",
"K c #c3c3c3",
"L c #c8c5c6",
"P c #cbcbcb",
"I c #d0cac8",
"U c #dfc6d5",
"Y c #d5d4d6",
"T c #dcd4d5",
"R c #d8d8d8",
"E c #f6f7db",
"W c Gray100",
"Q c None",
/* pixels */
"QQQQQQQQQQQQQQQQ",
"QQQQQQQQQQQQQQQQ",
"QQQQQQQQQQQQQQQQ",
"QQQQQ      QQQQQ",
"QQWO.dzer=K  QQQ",
"QQ wFn1:tkg$@ QQ",
"Q PTDn,  Pfiyq Q",
" 9UvZaoQQ &hSG7 ",
" 5NmH0 QQXRYbxu ",
"Q 36cC#.o2JEM4 Q",
"QQ splj*8IYVBXQQ",
"QQQ  %;-<>L  QQQ",
"QQQQQ      QQQQQ",
"QQQQQQQQQQQQQQQQ",
"QQQQQQQQQQQQQQQQ",
"QQQQQQQQQQQQQQQQ"
};
/* XPM */
static const char * const px_artist[] = {
/* columns rows colors chars-per-pixel */
"16 16 5 1",
"  c Gray0",
". c #949194",
"X c #deddde",
"o c Gray100",
"O c None",
/* pixels */
"OOOOOOOOOO XX OO",
"OOOOOOOOOO XX OO",
"OOOOOOOOO XX OOO",
"OOOOOOOOO XX OOO",
"OOOOOOOO XX OOOO",
"OOOOOOOO XX OOOO",
"OOOOOOO XX OOOOO",
"OOOOOOO XX OOOOO",
"OOOOOO    OOOOOO",
"OOOOO XX  OOOOOO",
"OOOO ooX  OOOOOO",
"OOOO oX.  OOOOOO",
"OOO oX.  OOOOOOO",
"OOO X.  OOOOOOOO",
"OO o.  OOOOOOOOO",
"O    OOOOOOOOOOO"
};
/* XPM */
static const char * const px_track[] = {
/* columns rows colors chars-per-pixel */
"16 16 5 1",
"  c Gray0",
". c #7c7c7c",
"X c #bcbcbc",
"o c Gray100",
"O c None",
/* pixels */
"OOOOOOOOOOOOOOOO",
"OOOOOO   OOOOOOO",
"OOOOO  .   OOOOO",
"OOOOO  oo.   OOO",
"OOOOO   .oo.  OO",
"OOOOO     .oo  O",
"OOOOO  OO   .  O",
"OO     OOOO    O",
"O  X.  OOOOOO  O",
"O .    OOOOOO  O",
"O     OOOO     O",
"OO   OOOO  X.  O",
"OOOOOOOOO .    O",
"OOOOOOOOO     OO",
"OOOOOOOOOO   OOO",
"OOOOOOOOOOOOOOOO"
};
/* XPM */
static const char * const px_next[] = {
/* columns rows colors chars-per-pixel */
"16 16 10 1",
"  c Gray0",
". c #3a3a3a",
"X c #555555",
"o c Gray44",
"O c Gray55",
"+ c #a7a7a7",
"@ c #cecece",
"# c #efefef",
"$ c Gray100",
"% c None",
/* pixels */
"%%%%%%%%%%%%%%%%",
"%%%%%%%%%%%%%%%%",
"%%% %%%%%%%% %%%",
"%% $ %%%%%% % %%",
"%% %$ %%%%% $ %%",
"%% $%$ %%%% % %%",
"%% %$%$ %%% $ %%",
"%% $%$%$ %% % %%",
"%% %$%$% %% $ %%",
"%% $%$% %%% % %%",
"%% %$% %%%% $ %%",
"%% $% %%%%% % %%",
"%% % %%%%%% $ %%",
"%%% %%%%%%%% %%%",
"%%%%%%%%%%%%%%%%",
"%%%%%%%%%%%%%%%%"
};
/* XPM */
static const char * const px_pause[] = {
/* columns rows colors chars-per-pixel */
"16 16 16 1",
"  c Gray0",
". c #4c4c4c",
"X c #505050",
"o c Gray39",
"O c Gray41",
"+ c #777777",
"@ c #7b7b7b",
"# c #818181",
"$ c #939393",
"% c #9a9a9a",
"& c #acacac",
"* c #b2b2b2",
"= c #dddddd",
"- c #efefef",
"; c Gray100",
": c None",
/* pixels */
"::::::::::::::::",
"::::::::::::::::",
"::::  ::::  ::::",
"::: ;: :: ;: :::",
"::: :; :: :; :::",
"::: ;: :: ;: :::",
"::: :; :: :; :::",
"::: ;: :: ;: :::",
"::: :; :: :; :::",
"::: ;: :: ;: :::",
"::: :; :: :; :::",
"::: ;: :: ;: :::",
"::: :; :: :; :::",
"::::  ::::  ::::",
"::::::::::::::::",
"::::::::::::::::"
};
/* XPM */
static const char * const px_play[] = {
/* columns rows colors chars-per-pixel */
"16 16 24 1",
"  c Gray0",
". c #0b0b0b",
"X c Gray8",
"o c #1d1d1d",
"O c #252525",
"+ c Gray17",
"@ c #353535",
"# c #3c3c3c",
"$ c #444444",
"% c #4c4c4c",
"& c Gray33",
"* c #5b5b5b",
"= c Gray38",
"- c #6a6a6a",
"; c #747474",
": c Gray52",
"> c #8b8b8b",
", c #9f9f9f",
"< c #a2a2a2",
"1 c #b9b9b9",
"2 c #dddddd",
"3 c #efefef",
"4 c Gray100",
"5 c None",
/* pixels */
"5555555555555555",
"5555555555555555",
"555  55555555555",
"55 54  555555555",
"55 4545  5555555",
"55 545454  55555",
"55 45454545  555",
"55 5454545454 55",
"55 4545454545 55",
"55 54545454  555",
"55 454545  55555",
"55 5454  5555555",
"55 45  555555555",
"555  55555555555",
"5555555555555555",
"5555555555555555"
};
/* XPM */
static const char * const px_previous[] = {
/* columns rows colors chars-per-pixel */
"16 16 17 1",
"  c Gray0",
". c #2d2d2d",
"X c #393939",
"o c Gray31",
"O c #515151",
"+ c Gray36",
"@ c Gray39",
"# c Gray46",
"$ c #7c7c7c",
"% c Gray58",
"& c #9a9a9a",
"* c #a2a2a2",
"= c #c5c5c5",
"- c #dddddd",
"; c #efefef",
": c Gray100",
"> c None",
/* pixels */
">>>>>>>>>>>>>>>>",
">>>>>>>>>>>>>>>>",
">>> >>>>>>>> >>>",
">> > >>>>>> : >>",
">> : >>>>> :> >>",
">> > >>>> :>: >>",
">> : >>> :>:> >>",
">> > >> :>:>: >>",
">> : >> >:>:> >>",
">> > >>> >:>: >>",
">> : >>>> >:> >>",
">> > >>>>> >: >>",
">> : >>>>>> > >>",
">>> >>>>>>>> >>>",
">>>>>>>>>>>>>>>>",
">>>>>>>>>>>>>>>>"
};
/* XPM */
static const char * const px_stop[] = {
/* columns rows colors chars-per-pixel */
"16 16 6 1",
"  c Gray0",
". c Gray4",
"X c #dddddd",
"o c #efefef",
"O c Gray100",
"+ c None",
/* pixels */
"++++++++++++++++",
"++++++++++++++++",
"+++  ..   .  +++",
"++ +O+O+O+O+O ++",
"++ O+O+O+O+O+ ++",
"++ +O+O+O+O+O ++",
"++ O+O+O+O+O+ ++",
"++ +O+O+O+O+O ++",
"++ O+O+O+O+O+ ++",
"++ +O+O+O+O+O ++",
"++ O+O+O+O+O+ ++",
"++ +O+O+O+O+O ++",
"++ O+O+O+O+O+ ++",
"+++          +++",
"++++++++++++++++",
"++++++++++++++++"
};

/* XPM */
static const char * const px_config[] = {
"16 16 3 1",
" 	c None",
".	c #000000",
"+	c #FFFFFF",
"                ",
"    ...         ",
"    .+ .        ",
"     .+ .       ",
" ..  . +.       ",
" .+.. + .       ",
" . + + + .      ",
"  . + + + ...   ",
"   ... + + + .  ",
"      . + + + . ",
"       . + ..+. ",
"       .+ .  .. ",
"       . +.     ",
"        . +.    ",
"         ...    ",
"                "};

/* XPM */
static const char * const px_x[] = {
"12 12 3 1",
" 	c None",
".	c #000000",
"+	c #FFFFFF",
"            ",
"  .      .  ",
" ...    ... ",
"  ...  ...  ",
"   ......   ",
"    ....    ",
"    ....    ",
"   ......   ",
"  ...  ...  ",
" ...    ... ",
"  .      .  ",
"            "};


/* XPM */
static const char * const px_plus[] = {
"12 12 3 1",
" 	c None",
".	c #000000",
"+	c #FFFFFF",
"            ",
"     ..     ",
"     ..     ",
"     ..     ",
"     ..     ",
" .......... ",
" .......... ",
"     ..     ",
"     ..     ",
"     ..     ",
"     ..     ",
"            "};

/* XPM */
static const char * const px_minus[] = {
"12 12 3 1",
" 	c None",
".	c #000000",
"+	c #FFFFFF",
"            ",
"            ",
"            ",
"            ",
"            ",
" .......... ",
" .......... ",
"            ",
"            ",
"            ",
"            ",
"            "};
